{"name": "test_failed", "status": "broken", "statusDetails": {"message": "ValueError", "trace": "def test_failed():\n>       raise ValueError\nE       ValueError\n\nunittests/test_main.py:25: ValueError"}, "start": 1744372241493, "stop": 1744372241493, "uuid": "733918b7-e741-40c8-a3c5-3813b0d8d57a", "historyId": "65e2bb9d8c7a9b25f0957bf4d40b3f97", "testCaseId": "65e2bb9d8c7a9b25f0957bf4d40b3f97", "fullName": "unittests.test_main#test_failed", "labels": [{"name": "parentSuite", "value": "unittests"}, {"name": "suite", "value": "test_main"}, {"name": "host", "value": "HenryLeedeMacBook-Pro.local"}, {"name": "thread", "value": "64896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unittests.test_main"}]}
