{"name": "test_failed", "status": "broken", "statusDetails": {"message": "ValueError", "trace": "def test_failed():\n>       raise ValueError\nE       ValueError\n\nunittests/test_main.py:26: ValueError"}, "start": 1744554489308, "stop": 1744554489308, "uuid": "ddbc8193-325a-4a73-8b4e-46ae69c8441f", "historyId": "65e2bb9d8c7a9b25f0957bf4d40b3f97", "testCaseId": "65e2bb9d8c7a9b25f0957bf4d40b3f97", "fullName": "unittests.test_main#test_failed", "labels": [{"name": "parentSuite", "value": "unittests"}, {"name": "suite", "value": "test_main"}, {"name": "host", "value": "HenryLeedeMacBook-Pro.local"}, {"name": "thread", "value": "7445-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unittests.test_main"}]}
